-- Seed master_food_classifications for Food Intelligence Layer (Milestone 3).
-- Run after master-nutrition-schema.sql.

insert into public.master_food_classifications (search_key, food_type, food_state_key, confidence, rules)
values
  ('chicken biryani', 'mixed_recipe', 'cooked', 0.92, '{"route":"recipe_template"}'::jsonb),
  ('veg biryani', 'mixed_recipe', 'cooked', 0.92, '{"route":"recipe_template"}'::jsonb),
  ('vegetable biryani', 'mixed_recipe', 'cooked', 0.9, '{"route":"recipe_template"}'::jsonb),
  ('chicken curry', 'mixed_recipe', 'cooked', 0.92, '{"route":"recipe_template"}'::jsonb),
  ('paneer butter masala', 'mixed_recipe', 'cooked', 0.9, '{"route":"recipe_template"}'::jsonb),
  ('dal tadka', 'mixed_recipe', 'cooked', 0.88, '{"route":"recipe_template"}'::jsonb),
  ('dal', 'cooked_side', 'cooked', 0.86, '{"canonical":"dal"}'::jsonb),
  ('shrimp curry', 'mixed_recipe', 'cooked', 0.92, '{"route":"recipe_template"}'::jsonb),
  ('prawn curry', 'mixed_recipe', 'cooked', 0.92, '{"route":"recipe_template","canonical":"shrimp curry"}'::jsonb),
  ('pasta', 'mixed_recipe', 'cooked', 0.88, '{"route":"recipe_template"}'::jsonb),
  ('sandwich', 'mixed_recipe', 'assembled', 0.88, '{"route":"recipe_template"}'::jsonb),
  ('smoothie', 'beverage', 'blended', 0.86, '{"route":"recipe_template"}'::jsonb),
  ('pizza', 'mixed_recipe', 'baked', 0.88, '{"route":"recipe_template"}'::jsonb),
  ('bhindi sabzi', 'cooked_side', 'fried', 0.88, '{"aliases":["bhindi","okra fry","lady finger"]}'::jsonb),
  ('okra fry', 'cooked_side', 'fried', 0.88, '{"canonical":"bhindi sabzi"}'::jsonb),
  ('lady finger', 'cooked_side', 'fried', 0.85, '{"canonical":"bhindi sabzi"}'::jsonb),
  ('boiled egg', 'simple_ingredient', 'boiled', 0.9, '{}'::jsonb),
  ('fried egg', 'simple_ingredient', 'fried', 0.9, '{}'::jsonb),
  ('grilled chicken', 'simple_ingredient', 'grilled', 0.88, '{}'::jsonb),
  ('roasted chicken', 'simple_ingredient', 'roasted', 0.88, '{}'::jsonb),
  ('steamed rice', 'cooked_side', 'steamed', 0.88, '{}'::jsonb),
  ('cooked rice', 'cooked_side', 'cooked', 0.88, '{}'::jsonb),
  ('white rice', 'cooked_side', 'cooked', 0.85, '{}'::jsonb),
  ('raw rice', 'simple_ingredient', 'dry', 0.85, '{}'::jsonb),
  ('chapati', 'cooked_side', 'cooked', 0.88, '{}'::jsonb),
  ('roti', 'cooked_side', 'cooked', 0.88, '{}'::jsonb),
  ('dosa', 'cooked_side', 'cooked', 0.88, '{}'::jsonb),
  ('idli', 'cooked_side', 'steamed', 0.88, '{}'::jsonb),
  ('sambar', 'mixed_recipe', 'cooked', 0.85, '{}'::jsonb),
  ('rasam', 'mixed_recipe', 'cooked', 0.85, '{}'::jsonb),
  ('chole', 'mixed_recipe', 'cooked', 0.85, '{}'::jsonb),
  ('rajma', 'mixed_recipe', 'cooked', 0.85, '{}'::jsonb),
  ('banana', 'simple_ingredient', 'raw', 0.9, '{}'::jsonb),
  ('apple', 'simple_ingredient', 'raw', 0.9, '{}'::jsonb),
  ('mango', 'simple_ingredient', 'raw', 0.9, '{}'::jsonb),
  ('spinach', 'simple_ingredient', 'raw', 0.88, '{}'::jsonb),
  ('onion', 'simple_ingredient', 'raw', 0.88, '{}'::jsonb),
  ('tomato', 'simple_ingredient', 'raw', 0.88, '{}'::jsonb),
  ('garam masala', 'tiny_garnish', 'dry', 0.9, '{}'::jsonb),
  ('turmeric', 'tiny_garnish', 'dry', 0.9, '{}'::jsonb),
  ('coriander leaves', 'tiny_garnish', 'raw', 0.88, '{}'::jsonb),
  ('green chili', 'tiny_garnish', 'raw', 0.88, '{}'::jsonb),
  ('lime', 'tiny_garnish', 'raw', 0.9, '{"tiny_profile":"lime"}'::jsonb),
  ('lime wedge', 'tiny_garnish', 'raw', 0.9, '{"tiny_profile":"lime"}'::jsonb),
  ('lemon', 'tiny_garnish', 'raw', 0.9, '{"tiny_profile":"lemon"}'::jsonb),
  ('lemon wedge', 'tiny_garnish', 'raw', 0.9, '{"tiny_profile":"lemon"}'::jsonb),
  ('mint', 'tiny_garnish', 'raw', 0.88, '{}'::jsonb),
  ('curry leaves', 'tiny_garnish', 'raw', 0.88, '{}'::jsonb),
  ('ginger', 'tiny_garnish', 'raw', 0.88, '{}'::jsonb),
  ('garlic', 'tiny_garnish', 'raw', 0.88, '{}'::jsonb),
  ('cadbury', 'branded_packaged', 'unknown', 0.85, '{"lookup":"branded"}'::jsonb),
  ('amul', 'branded_packaged', 'unknown', 0.85, '{"lookup":"branded"}'::jsonb),
  ('nestle', 'branded_packaged', 'unknown', 0.85, '{"lookup":"branded"}'::jsonb),
  ('zomato meal', 'unknown', 'cooked', 0.8, '{"reason":"restaurant_meal"}'::jsonb),
  ('swiggy meal', 'unknown', 'cooked', 0.8, '{"reason":"restaurant_meal"}'::jsonb)
on conflict (search_key) do update
set food_type = excluded.food_type,
    food_state_key = excluded.food_state_key,
    confidence = excluded.confidence,
    rules = excluded.rules,
    updated_at = now();
