export const SOURCE_REGISTRY = {
  ifct: { sourceKey: 'ifct', sourceName: 'Indian Food Composition Tables 2017', priority: 10, type: 'nutrition' },
  indb: { sourceKey: 'indb', sourceName: 'Indian Nutrient Database', priority: 20, type: 'nutrition' },
  usda: { sourceKey: 'usda_fdc', sourceName: 'USDA FoodData Central', priority: 30, type: 'nutrition' },
  usda_fdc: { sourceKey: 'usda_fdc', sourceName: 'USDA FoodData Central', priority: 30, type: 'nutrition' },
  fndds: { sourceKey: 'fndds', sourceName: 'Food and Nutrient Database for Dietary Studies', priority: 35, type: 'nutrition' },
  'open food facts': { sourceKey: 'open_food_facts', sourceName: 'Open Food Facts', priority: 40, type: 'branded_food' },
  open_food_facts: { sourceKey: 'open_food_facts', sourceName: 'Open Food Facts', priority: 40, type: 'branded_food' },
  off: { sourceKey: 'open_food_facts', sourceName: 'Open Food Facts', priority: 40, type: 'branded_food' },
  'recipe derived': { sourceKey: 'recipe_derived', sourceName: 'Recipe-derived aggregate', priority: 50, type: 'recipe' },
  'recipe-derived': { sourceKey: 'recipe_derived', sourceName: 'Recipe-derived aggregate', priority: 50, type: 'recipe' },
  recipe_derived: { sourceKey: 'recipe_derived', sourceName: 'Recipe-derived aggregate', priority: 50, type: 'recipe' },
  recipe_db: { sourceKey: 'recipe_db', sourceName: 'RecipeDB', priority: 51, type: 'recipe' },
  recipe_nlg: { sourceKey: 'recipe_nlg', sourceName: 'RecipeNLG', priority: 52, type: 'recipe' },
  recipe1m: { sourceKey: 'recipe1m', sourceName: 'Recipe1M+', priority: 53, type: 'recipe' },
  food_com: { sourceKey: 'food_com', sourceName: 'Food.com Recipes', priority: 54, type: 'recipe' },
  epicurious: { sourceKey: 'epicurious', sourceName: 'Epicurious Recipes', priority: 55, type: 'recipe' },
  indian_recipes_6000: { sourceKey: 'indian_recipes_6000', sourceName: '6000+ Indian Recipes', priority: 56, type: 'recipe' },
  indian_recipes_nutrition: { sourceKey: 'indian_recipes_nutrition', sourceName: 'Indian Recipes + Nutrition', priority: 57, type: 'recipe' },
  indian_recipes_cleaned: { sourceKey: 'indian_recipes_cleaned', sourceName: 'Cleaned Indian Recipes', priority: 58, type: 'recipe' },
  indori: { sourceKey: 'indori', sourceName: 'INDoRI', priority: 59, type: 'recipe' },
  ai: { sourceKey: 'ai_internal', sourceName: 'AI/Internal estimate', priority: 60, type: 'estimate' },
  internal: { sourceKey: 'ai_internal', sourceName: 'AI/Internal estimate', priority: 60, type: 'estimate' },
  'ai/internal estimates': { sourceKey: 'ai_internal', sourceName: 'AI/Internal estimate', priority: 60, type: 'estimate' },
};

export const COLUMN_ALIASES = {
  sourceName: ['source_name', 'source', 'dataset', 'data_source'],
  externalId: ['external_id', 'source_id', 'fdc_id', 'code', 'id', 'product_code', 'barcode'],
  foodName: ['food_name', 'name', 'canonical_name', 'product_name', 'recipe_name', 'dish_name', 'food'],
  category: ['category', 'food_category', 'group'],
  cuisine: ['cuisine', 'region_cuisine'],
  brand: ['brand', 'brands', 'brand_owner', 'manufacturer'],
  barcode: ['barcode', 'code', 'product_code', 'ean'],
  calories: ['calories_per_100g', 'energy_kcal_100g', 'energy-kcal_100g', 'kcal_100g', 'calories', 'energy_kcal'],
  protein: ['protein_per_100g', 'proteins_100g', 'protein_100g', 'protein', 'proteins'],
  carbs: ['carbs_per_100g', 'carbohydrates_100g', 'carbohydrate_100g', 'carbs_100g', 'carbohydrates', 'carbs'],
  fat: ['fat_per_100g', 'fats_per_100g', 'fat_100g', 'fats_100g', 'fat', 'fats'],
  fiber: ['fiber_per_100g', 'fibre_per_100g', 'fiber_100g', 'fibre_100g', 'fiber', 'fibre'],
  water: ['water_per_100g', 'water_100g', 'water'],
  servingName: ['serving_name', 'serving_unit', 'household_serving', 'portion_name', 'unit'],
  servingGrams: ['serving_grams', 'grams', 'serving_weight_g', 'portion_grams', 'quantity_g'],
  aliases: ['aliases', 'alias', 'alternate_names', 'synonyms', 'common_names'],
  language: ['language', 'lang'],
  region: ['region', 'state'],
  recipeIngredients: ['recipe_ingredients', 'ingredients', 'ingredient_percentages', 'template_items'],
  stateKey: ['state_key', 'food_state', 'preparation_state', 'state'],
};

export const KNOWN_CANONICAL_ALIASES = new Map([
  ['lady finger', 'bhindi sabzi'],
  ['ladies finger', 'bhindi sabzi'],
  ['okra', 'bhindi sabzi'],
  ['okra fry', 'bhindi sabzi'],
  ['fried okra', 'bhindi sabzi'],
  ['bhindi', 'bhindi sabzi'],
  ['bhindi fry', 'bhindi sabzi'],
  ['chicken curry indian', 'chicken curry'],
  ['home style chicken curry', 'chicken curry'],
  ['ready chicken curry', 'chicken curry'],
  ['rice', 'white rice'],
  ['white rice', 'white rice'],
  ['cooked rice', 'white rice'],
  ['cooked white rice', 'white rice'],
  ['chawal', 'white rice'],
  ['bhaat', 'white rice'],
  ['roti', 'chapati'],
  ['phulka', 'chapati'],
  ['fulka', 'chapati'],
  ['rotli', 'chapati'],
  ['dal chawal', 'dal rice'],
  ['rice with dal', 'dal rice'],
  ['hyderabadi chicken biryani', 'chicken biryani'],
  ['chicken biryani hyderabadi', 'chicken biryani'],
  ['lady finger curry', 'bhindi sabzi'],
  ['okra curry', 'bhindi sabzi'],
  ['sambhar', 'sambar'],
  ['aval upma', 'poha'],
  ['pohe', 'poha'],
]);

export const resolveSource = (sourceName) => {
  const key = String(sourceName || '').trim().toLowerCase();
  return SOURCE_REGISTRY[key] || {
    sourceKey: key.replace(/\s+/g, '_') || 'unknown',
    sourceName: String(sourceName || 'Unknown').trim() || 'Unknown',
    priority: 99,
    type: 'nutrition',
  };
};

export const sourcePriority = (sourceName) => resolveSource(sourceName).priority;
