from pathlib import Path
import re

from pypdf import PdfReader


ROOT = Path(__file__).resolve().parents[1]
INPUT_PATH = ROOT / "raw_datasets" / "workouts" / "compendium" / "1_2024-adult-compendium_1_2024.pdf"
OUTPUT_DIR = ROOT / "supabase" / "imports"
OUTPUT_PATH = OUTPUT_DIR / "master_activity_mets_load.sql"
SOURCE_KEY = "adult_compendium_2024"
SOURCE_URL = "https://pacompendium.com/adult-compendium/"


def sql_quote(value):
    if value is None or value == "":
        return "null"
    return "'" + str(value).replace("'", "''") + "'"


def search_key(value):
    text = sanitize_text(value).lower().replace("&", " and ")
    text = re.sub(r"[^a-z0-9]+", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def sanitize_text(value):
    text = str(value or "")
    replacements = {
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2013": "-",
        "\u2014": "-",
        "\u2122": "",
        "\u00ae": "",
        "\u00a9": "",
        "\u00b7": "-",
        "\u00a0": " ",
        "â€“": "-",
        "â€”": "-",
        "â€˜": "'",
        "â€™": "'",
        "â€œ": '"',
        "â€\u009d": '"',
        "â„¢": "",
    }
    for original, replacement in replacements.items():
        text = text.replace(original, replacement)
    return text.encode("ascii", "ignore").decode("ascii")


def compact_line(value):
    return " ".join(sanitize_text(value).split())


def extract_rows(pdf_path):
    reader = PdfReader(str(pdf_path))
    row_re = re.compile(r"^(?P<heading>.+?)\s+(?P<code>\d{5})\s+(?P<met>\d+(?:\.\d+)?)\s+(?P<description>.+)$")
    rows = []

    for page in reader.pages:
        text = page.extract_text() or ""
        for raw_line in text.splitlines():
            line = compact_line(raw_line)
            if not line:
                continue
            if line.startswith("Major Heading ") or line == "2024 Adult Compendium of Physical Activities":
                continue

            match = row_re.match(line)
            if match:
                row = match.groupdict()
                row["heading"] = compact_line(row["heading"])
                row["description"] = compact_line(row["description"])
                rows.append(row)
            elif rows and not re.fullmatch(r"\d+", line):
                rows[-1]["description"] = compact_line(rows[-1]["description"] + " " + line)

    return rows


def build_upsert(row):
    description = row["description"]
    return f"""
insert into public.master_activity_mets (
  major_heading, activity_code, met_value, description, search_key, source_key, source_url, active
)
values (
  {sql_quote(row["heading"])},
  {sql_quote(row["code"])},
  {float(row["met"])},
  {sql_quote(description)},
  {sql_quote(search_key(description))},
  {sql_quote(SOURCE_KEY)},
  {sql_quote(SOURCE_URL)},
  true
)
on conflict (source_key, activity_code) do update set
  major_heading = excluded.major_heading,
  met_value = excluded.met_value,
  description = excluded.description,
  search_key = excluded.search_key,
  source_url = excluded.source_url,
  active = excluded.active,
  updated_at = now();"""


def main():
    if not INPUT_PATH.exists():
        raise SystemExit(f"Missing {INPUT_PATH.relative_to(ROOT)}")

    rows = extract_rows(INPUT_PATH)
    if len(rows) < 500:
        raise SystemExit(f"Only parsed {len(rows)} rows; expected the full compendium.")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    sql = (
        "-- Auto-generated by scripts/build-master-activity-met-sql.py\n"
        "-- Run after supabase/master-activity-mets-schema.sql.\n\n"
        "begin;\n\n"
        + "\n".join(build_upsert(row) for row in rows)
        + "\n\ncommit;\n"
    )
    OUTPUT_PATH.write_text(sql, encoding="utf-8")

    print("Master activity MET import SQL generated")
    print(f"Input: {INPUT_PATH.relative_to(ROOT)}")
    print(f"Activities: {len(rows)}")
    print(f"Output: {OUTPUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
